
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `ErrorReport` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model ErrorReport
 * 
 */
export type ErrorReportModel = runtime.Types.Result.DefaultSelection<Prisma.$ErrorReportPayload>

export type AggregateErrorReport = {
  _count: ErrorReportCountAggregateOutputType | null
  _min: ErrorReportMinAggregateOutputType | null
  _max: ErrorReportMaxAggregateOutputType | null
}

export type ErrorReportMinAggregateOutputType = {
  id: string | null
  playerId: string | null
  type: string | null
  title: string | null
  description: string | null
  status: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type ErrorReportMaxAggregateOutputType = {
  id: string | null
  playerId: string | null
  type: string | null
  title: string | null
  description: string | null
  status: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type ErrorReportCountAggregateOutputType = {
  id: number
  playerId: number
  type: number
  title: number
  description: number
  status: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type ErrorReportMinAggregateInputType = {
  id?: true
  playerId?: true
  type?: true
  title?: true
  description?: true
  status?: true
  createdAt?: true
  updatedAt?: true
}

export type ErrorReportMaxAggregateInputType = {
  id?: true
  playerId?: true
  type?: true
  title?: true
  description?: true
  status?: true
  createdAt?: true
  updatedAt?: true
}

export type ErrorReportCountAggregateInputType = {
  id?: true
  playerId?: true
  type?: true
  title?: true
  description?: true
  status?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type ErrorReportAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which ErrorReport to aggregate.
   */
  where?: Prisma.ErrorReportWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ErrorReports to fetch.
   */
  orderBy?: Prisma.ErrorReportOrderByWithRelationInput | Prisma.ErrorReportOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.ErrorReportWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ErrorReports from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ErrorReports.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned ErrorReports
  **/
  _count?: true | ErrorReportCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: ErrorReportMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: ErrorReportMaxAggregateInputType
}

export type GetErrorReportAggregateType<T extends ErrorReportAggregateArgs> = {
      [P in keyof T & keyof AggregateErrorReport]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateErrorReport[P]>
    : Prisma.GetScalarType<T[P], AggregateErrorReport[P]>
}




export type ErrorReportGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ErrorReportWhereInput
  orderBy?: Prisma.ErrorReportOrderByWithAggregationInput | Prisma.ErrorReportOrderByWithAggregationInput[]
  by: Prisma.ErrorReportScalarFieldEnum[] | Prisma.ErrorReportScalarFieldEnum
  having?: Prisma.ErrorReportScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: ErrorReportCountAggregateInputType | true
  _min?: ErrorReportMinAggregateInputType
  _max?: ErrorReportMaxAggregateInputType
}

export type ErrorReportGroupByOutputType = {
  id: string
  playerId: string | null
  type: string
  title: string
  description: string
  status: string
  createdAt: Date
  updatedAt: Date
  _count: ErrorReportCountAggregateOutputType | null
  _min: ErrorReportMinAggregateOutputType | null
  _max: ErrorReportMaxAggregateOutputType | null
}

type GetErrorReportGroupByPayload<T extends ErrorReportGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<ErrorReportGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof ErrorReportGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], ErrorReportGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], ErrorReportGroupByOutputType[P]>
      }
    >
  >



export type ErrorReportWhereInput = {
  AND?: Prisma.ErrorReportWhereInput | Prisma.ErrorReportWhereInput[]
  OR?: Prisma.ErrorReportWhereInput[]
  NOT?: Prisma.ErrorReportWhereInput | Prisma.ErrorReportWhereInput[]
  id?: Prisma.StringFilter<"ErrorReport"> | string
  playerId?: Prisma.StringNullableFilter<"ErrorReport"> | string | null
  type?: Prisma.StringFilter<"ErrorReport"> | string
  title?: Prisma.StringFilter<"ErrorReport"> | string
  description?: Prisma.StringFilter<"ErrorReport"> | string
  status?: Prisma.StringFilter<"ErrorReport"> | string
  createdAt?: Prisma.DateTimeFilter<"ErrorReport"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"ErrorReport"> | Date | string
}

export type ErrorReportOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  playerId?: Prisma.SortOrderInput | Prisma.SortOrder
  type?: Prisma.SortOrder
  title?: Prisma.SortOrder
  description?: Prisma.SortOrder
  status?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type ErrorReportWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.ErrorReportWhereInput | Prisma.ErrorReportWhereInput[]
  OR?: Prisma.ErrorReportWhereInput[]
  NOT?: Prisma.ErrorReportWhereInput | Prisma.ErrorReportWhereInput[]
  playerId?: Prisma.StringNullableFilter<"ErrorReport"> | string | null
  type?: Prisma.StringFilter<"ErrorReport"> | string
  title?: Prisma.StringFilter<"ErrorReport"> | string
  description?: Prisma.StringFilter<"ErrorReport"> | string
  status?: Prisma.StringFilter<"ErrorReport"> | string
  createdAt?: Prisma.DateTimeFilter<"ErrorReport"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"ErrorReport"> | Date | string
}, "id">

export type ErrorReportOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  playerId?: Prisma.SortOrderInput | Prisma.SortOrder
  type?: Prisma.SortOrder
  title?: Prisma.SortOrder
  description?: Prisma.SortOrder
  status?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.ErrorReportCountOrderByAggregateInput
  _max?: Prisma.ErrorReportMaxOrderByAggregateInput
  _min?: Prisma.ErrorReportMinOrderByAggregateInput
}

export type ErrorReportScalarWhereWithAggregatesInput = {
  AND?: Prisma.ErrorReportScalarWhereWithAggregatesInput | Prisma.ErrorReportScalarWhereWithAggregatesInput[]
  OR?: Prisma.ErrorReportScalarWhereWithAggregatesInput[]
  NOT?: Prisma.ErrorReportScalarWhereWithAggregatesInput | Prisma.ErrorReportScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"ErrorReport"> | string
  playerId?: Prisma.StringNullableWithAggregatesFilter<"ErrorReport"> | string | null
  type?: Prisma.StringWithAggregatesFilter<"ErrorReport"> | string
  title?: Prisma.StringWithAggregatesFilter<"ErrorReport"> | string
  description?: Prisma.StringWithAggregatesFilter<"ErrorReport"> | string
  status?: Prisma.StringWithAggregatesFilter<"ErrorReport"> | string
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"ErrorReport"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"ErrorReport"> | Date | string
}

export type ErrorReportCreateInput = {
  id?: string
  playerId?: string | null
  type: string
  title: string
  description: string
  status?: string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type ErrorReportUncheckedCreateInput = {
  id?: string
  playerId?: string | null
  type: string
  title: string
  description: string
  status?: string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type ErrorReportUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  playerId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  type?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ErrorReportUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  playerId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  type?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ErrorReportCreateManyInput = {
  id?: string
  playerId?: string | null
  type: string
  title: string
  description: string
  status?: string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type ErrorReportUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  playerId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  type?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ErrorReportUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  playerId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  type?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ErrorReportCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  playerId?: Prisma.SortOrder
  type?: Prisma.SortOrder
  title?: Prisma.SortOrder
  description?: Prisma.SortOrder
  status?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type ErrorReportMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  playerId?: Prisma.SortOrder
  type?: Prisma.SortOrder
  title?: Prisma.SortOrder
  description?: Prisma.SortOrder
  status?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type ErrorReportMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  playerId?: Prisma.SortOrder
  type?: Prisma.SortOrder
  title?: Prisma.SortOrder
  description?: Prisma.SortOrder
  status?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}



export type ErrorReportSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  playerId?: boolean
  type?: boolean
  title?: boolean
  description?: boolean
  status?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["errorReport"]>

export type ErrorReportSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  playerId?: boolean
  type?: boolean
  title?: boolean
  description?: boolean
  status?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["errorReport"]>

export type ErrorReportSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  playerId?: boolean
  type?: boolean
  title?: boolean
  description?: boolean
  status?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["errorReport"]>

export type ErrorReportSelectScalar = {
  id?: boolean
  playerId?: boolean
  type?: boolean
  title?: boolean
  description?: boolean
  status?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type ErrorReportOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "playerId" | "type" | "title" | "description" | "status" | "createdAt" | "updatedAt", ExtArgs["result"]["errorReport"]>

export type $ErrorReportPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "ErrorReport"
  objects: {}
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    playerId: string | null
    type: string
    title: string
    description: string
    status: string
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["errorReport"]>
  composites: {}
}

export type ErrorReportGetPayload<S extends boolean | null | undefined | ErrorReportDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$ErrorReportPayload, S>

export type ErrorReportCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<ErrorReportFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: ErrorReportCountAggregateInputType | true
  }

export interface ErrorReportDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['ErrorReport'], meta: { name: 'ErrorReport' } }
  /**
   * Find zero or one ErrorReport that matches the filter.
   * @param {ErrorReportFindUniqueArgs} args - Arguments to find a ErrorReport
   * @example
   * // Get one ErrorReport
   * const errorReport = await prisma.errorReport.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends ErrorReportFindUniqueArgs>(args: Prisma.SelectSubset<T, ErrorReportFindUniqueArgs<ExtArgs>>): Prisma.Prisma__ErrorReportClient<runtime.Types.Result.GetResult<Prisma.$ErrorReportPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one ErrorReport that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {ErrorReportFindUniqueOrThrowArgs} args - Arguments to find a ErrorReport
   * @example
   * // Get one ErrorReport
   * const errorReport = await prisma.errorReport.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends ErrorReportFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, ErrorReportFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__ErrorReportClient<runtime.Types.Result.GetResult<Prisma.$ErrorReportPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first ErrorReport that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ErrorReportFindFirstArgs} args - Arguments to find a ErrorReport
   * @example
   * // Get one ErrorReport
   * const errorReport = await prisma.errorReport.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends ErrorReportFindFirstArgs>(args?: Prisma.SelectSubset<T, ErrorReportFindFirstArgs<ExtArgs>>): Prisma.Prisma__ErrorReportClient<runtime.Types.Result.GetResult<Prisma.$ErrorReportPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first ErrorReport that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ErrorReportFindFirstOrThrowArgs} args - Arguments to find a ErrorReport
   * @example
   * // Get one ErrorReport
   * const errorReport = await prisma.errorReport.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends ErrorReportFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, ErrorReportFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__ErrorReportClient<runtime.Types.Result.GetResult<Prisma.$ErrorReportPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more ErrorReports that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ErrorReportFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all ErrorReports
   * const errorReports = await prisma.errorReport.findMany()
   * 
   * // Get first 10 ErrorReports
   * const errorReports = await prisma.errorReport.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const errorReportWithIdOnly = await prisma.errorReport.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends ErrorReportFindManyArgs>(args?: Prisma.SelectSubset<T, ErrorReportFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ErrorReportPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a ErrorReport.
   * @param {ErrorReportCreateArgs} args - Arguments to create a ErrorReport.
   * @example
   * // Create one ErrorReport
   * const ErrorReport = await prisma.errorReport.create({
   *   data: {
   *     // ... data to create a ErrorReport
   *   }
   * })
   * 
   */
  create<T extends ErrorReportCreateArgs>(args: Prisma.SelectSubset<T, ErrorReportCreateArgs<ExtArgs>>): Prisma.Prisma__ErrorReportClient<runtime.Types.Result.GetResult<Prisma.$ErrorReportPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many ErrorReports.
   * @param {ErrorReportCreateManyArgs} args - Arguments to create many ErrorReports.
   * @example
   * // Create many ErrorReports
   * const errorReport = await prisma.errorReport.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends ErrorReportCreateManyArgs>(args?: Prisma.SelectSubset<T, ErrorReportCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many ErrorReports and returns the data saved in the database.
   * @param {ErrorReportCreateManyAndReturnArgs} args - Arguments to create many ErrorReports.
   * @example
   * // Create many ErrorReports
   * const errorReport = await prisma.errorReport.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many ErrorReports and only return the `id`
   * const errorReportWithIdOnly = await prisma.errorReport.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends ErrorReportCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, ErrorReportCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ErrorReportPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a ErrorReport.
   * @param {ErrorReportDeleteArgs} args - Arguments to delete one ErrorReport.
   * @example
   * // Delete one ErrorReport
   * const ErrorReport = await prisma.errorReport.delete({
   *   where: {
   *     // ... filter to delete one ErrorReport
   *   }
   * })
   * 
   */
  delete<T extends ErrorReportDeleteArgs>(args: Prisma.SelectSubset<T, ErrorReportDeleteArgs<ExtArgs>>): Prisma.Prisma__ErrorReportClient<runtime.Types.Result.GetResult<Prisma.$ErrorReportPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one ErrorReport.
   * @param {ErrorReportUpdateArgs} args - Arguments to update one ErrorReport.
   * @example
   * // Update one ErrorReport
   * const errorReport = await prisma.errorReport.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends ErrorReportUpdateArgs>(args: Prisma.SelectSubset<T, ErrorReportUpdateArgs<ExtArgs>>): Prisma.Prisma__ErrorReportClient<runtime.Types.Result.GetResult<Prisma.$ErrorReportPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more ErrorReports.
   * @param {ErrorReportDeleteManyArgs} args - Arguments to filter ErrorReports to delete.
   * @example
   * // Delete a few ErrorReports
   * const { count } = await prisma.errorReport.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends ErrorReportDeleteManyArgs>(args?: Prisma.SelectSubset<T, ErrorReportDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more ErrorReports.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ErrorReportUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many ErrorReports
   * const errorReport = await prisma.errorReport.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends ErrorReportUpdateManyArgs>(args: Prisma.SelectSubset<T, ErrorReportUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more ErrorReports and returns the data updated in the database.
   * @param {ErrorReportUpdateManyAndReturnArgs} args - Arguments to update many ErrorReports.
   * @example
   * // Update many ErrorReports
   * const errorReport = await prisma.errorReport.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more ErrorReports and only return the `id`
   * const errorReportWithIdOnly = await prisma.errorReport.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends ErrorReportUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, ErrorReportUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ErrorReportPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one ErrorReport.
   * @param {ErrorReportUpsertArgs} args - Arguments to update or create a ErrorReport.
   * @example
   * // Update or create a ErrorReport
   * const errorReport = await prisma.errorReport.upsert({
   *   create: {
   *     // ... data to create a ErrorReport
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the ErrorReport we want to update
   *   }
   * })
   */
  upsert<T extends ErrorReportUpsertArgs>(args: Prisma.SelectSubset<T, ErrorReportUpsertArgs<ExtArgs>>): Prisma.Prisma__ErrorReportClient<runtime.Types.Result.GetResult<Prisma.$ErrorReportPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of ErrorReports.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ErrorReportCountArgs} args - Arguments to filter ErrorReports to count.
   * @example
   * // Count the number of ErrorReports
   * const count = await prisma.errorReport.count({
   *   where: {
   *     // ... the filter for the ErrorReports we want to count
   *   }
   * })
  **/
  count<T extends ErrorReportCountArgs>(
    args?: Prisma.Subset<T, ErrorReportCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], ErrorReportCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a ErrorReport.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ErrorReportAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends ErrorReportAggregateArgs>(args: Prisma.Subset<T, ErrorReportAggregateArgs>): Prisma.PrismaPromise<GetErrorReportAggregateType<T>>

  /**
   * Group by ErrorReport.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ErrorReportGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends ErrorReportGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: ErrorReportGroupByArgs['orderBy'] }
      : { orderBy?: ErrorReportGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, ErrorReportGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetErrorReportGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the ErrorReport model
 */
readonly fields: ErrorReportFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for ErrorReport.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__ErrorReportClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the ErrorReport model
 */
export interface ErrorReportFieldRefs {
  readonly id: Prisma.FieldRef<"ErrorReport", 'String'>
  readonly playerId: Prisma.FieldRef<"ErrorReport", 'String'>
  readonly type: Prisma.FieldRef<"ErrorReport", 'String'>
  readonly title: Prisma.FieldRef<"ErrorReport", 'String'>
  readonly description: Prisma.FieldRef<"ErrorReport", 'String'>
  readonly status: Prisma.FieldRef<"ErrorReport", 'String'>
  readonly createdAt: Prisma.FieldRef<"ErrorReport", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"ErrorReport", 'DateTime'>
}
    

// Custom InputTypes
/**
 * ErrorReport findUnique
 */
export type ErrorReportFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ErrorReport
   */
  select?: Prisma.ErrorReportSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ErrorReport
   */
  omit?: Prisma.ErrorReportOmit<ExtArgs> | null
  /**
   * Filter, which ErrorReport to fetch.
   */
  where: Prisma.ErrorReportWhereUniqueInput
}

/**
 * ErrorReport findUniqueOrThrow
 */
export type ErrorReportFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ErrorReport
   */
  select?: Prisma.ErrorReportSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ErrorReport
   */
  omit?: Prisma.ErrorReportOmit<ExtArgs> | null
  /**
   * Filter, which ErrorReport to fetch.
   */
  where: Prisma.ErrorReportWhereUniqueInput
}

/**
 * ErrorReport findFirst
 */
export type ErrorReportFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ErrorReport
   */
  select?: Prisma.ErrorReportSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ErrorReport
   */
  omit?: Prisma.ErrorReportOmit<ExtArgs> | null
  /**
   * Filter, which ErrorReport to fetch.
   */
  where?: Prisma.ErrorReportWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ErrorReports to fetch.
   */
  orderBy?: Prisma.ErrorReportOrderByWithRelationInput | Prisma.ErrorReportOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for ErrorReports.
   */
  cursor?: Prisma.ErrorReportWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ErrorReports from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ErrorReports.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ErrorReports.
   */
  distinct?: Prisma.ErrorReportScalarFieldEnum | Prisma.ErrorReportScalarFieldEnum[]
}

/**
 * ErrorReport findFirstOrThrow
 */
export type ErrorReportFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ErrorReport
   */
  select?: Prisma.ErrorReportSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ErrorReport
   */
  omit?: Prisma.ErrorReportOmit<ExtArgs> | null
  /**
   * Filter, which ErrorReport to fetch.
   */
  where?: Prisma.ErrorReportWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ErrorReports to fetch.
   */
  orderBy?: Prisma.ErrorReportOrderByWithRelationInput | Prisma.ErrorReportOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for ErrorReports.
   */
  cursor?: Prisma.ErrorReportWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ErrorReports from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ErrorReports.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ErrorReports.
   */
  distinct?: Prisma.ErrorReportScalarFieldEnum | Prisma.ErrorReportScalarFieldEnum[]
}

/**
 * ErrorReport findMany
 */
export type ErrorReportFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ErrorReport
   */
  select?: Prisma.ErrorReportSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ErrorReport
   */
  omit?: Prisma.ErrorReportOmit<ExtArgs> | null
  /**
   * Filter, which ErrorReports to fetch.
   */
  where?: Prisma.ErrorReportWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ErrorReports to fetch.
   */
  orderBy?: Prisma.ErrorReportOrderByWithRelationInput | Prisma.ErrorReportOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing ErrorReports.
   */
  cursor?: Prisma.ErrorReportWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ErrorReports from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ErrorReports.
   */
  skip?: number
  distinct?: Prisma.ErrorReportScalarFieldEnum | Prisma.ErrorReportScalarFieldEnum[]
}

/**
 * ErrorReport create
 */
export type ErrorReportCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ErrorReport
   */
  select?: Prisma.ErrorReportSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ErrorReport
   */
  omit?: Prisma.ErrorReportOmit<ExtArgs> | null
  /**
   * The data needed to create a ErrorReport.
   */
  data: Prisma.XOR<Prisma.ErrorReportCreateInput, Prisma.ErrorReportUncheckedCreateInput>
}

/**
 * ErrorReport createMany
 */
export type ErrorReportCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many ErrorReports.
   */
  data: Prisma.ErrorReportCreateManyInput | Prisma.ErrorReportCreateManyInput[]
}

/**
 * ErrorReport createManyAndReturn
 */
export type ErrorReportCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ErrorReport
   */
  select?: Prisma.ErrorReportSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the ErrorReport
   */
  omit?: Prisma.ErrorReportOmit<ExtArgs> | null
  /**
   * The data used to create many ErrorReports.
   */
  data: Prisma.ErrorReportCreateManyInput | Prisma.ErrorReportCreateManyInput[]
}

/**
 * ErrorReport update
 */
export type ErrorReportUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ErrorReport
   */
  select?: Prisma.ErrorReportSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ErrorReport
   */
  omit?: Prisma.ErrorReportOmit<ExtArgs> | null
  /**
   * The data needed to update a ErrorReport.
   */
  data: Prisma.XOR<Prisma.ErrorReportUpdateInput, Prisma.ErrorReportUncheckedUpdateInput>
  /**
   * Choose, which ErrorReport to update.
   */
  where: Prisma.ErrorReportWhereUniqueInput
}

/**
 * ErrorReport updateMany
 */
export type ErrorReportUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update ErrorReports.
   */
  data: Prisma.XOR<Prisma.ErrorReportUpdateManyMutationInput, Prisma.ErrorReportUncheckedUpdateManyInput>
  /**
   * Filter which ErrorReports to update
   */
  where?: Prisma.ErrorReportWhereInput
  /**
   * Limit how many ErrorReports to update.
   */
  limit?: number
}

/**
 * ErrorReport updateManyAndReturn
 */
export type ErrorReportUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ErrorReport
   */
  select?: Prisma.ErrorReportSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the ErrorReport
   */
  omit?: Prisma.ErrorReportOmit<ExtArgs> | null
  /**
   * The data used to update ErrorReports.
   */
  data: Prisma.XOR<Prisma.ErrorReportUpdateManyMutationInput, Prisma.ErrorReportUncheckedUpdateManyInput>
  /**
   * Filter which ErrorReports to update
   */
  where?: Prisma.ErrorReportWhereInput
  /**
   * Limit how many ErrorReports to update.
   */
  limit?: number
}

/**
 * ErrorReport upsert
 */
export type ErrorReportUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ErrorReport
   */
  select?: Prisma.ErrorReportSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ErrorReport
   */
  omit?: Prisma.ErrorReportOmit<ExtArgs> | null
  /**
   * The filter to search for the ErrorReport to update in case it exists.
   */
  where: Prisma.ErrorReportWhereUniqueInput
  /**
   * In case the ErrorReport found by the `where` argument doesn't exist, create a new ErrorReport with this data.
   */
  create: Prisma.XOR<Prisma.ErrorReportCreateInput, Prisma.ErrorReportUncheckedCreateInput>
  /**
   * In case the ErrorReport was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.ErrorReportUpdateInput, Prisma.ErrorReportUncheckedUpdateInput>
}

/**
 * ErrorReport delete
 */
export type ErrorReportDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ErrorReport
   */
  select?: Prisma.ErrorReportSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ErrorReport
   */
  omit?: Prisma.ErrorReportOmit<ExtArgs> | null
  /**
   * Filter which ErrorReport to delete.
   */
  where: Prisma.ErrorReportWhereUniqueInput
}

/**
 * ErrorReport deleteMany
 */
export type ErrorReportDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which ErrorReports to delete
   */
  where?: Prisma.ErrorReportWhereInput
  /**
   * Limit how many ErrorReports to delete.
   */
  limit?: number
}

/**
 * ErrorReport without action
 */
export type ErrorReportDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ErrorReport
   */
  select?: Prisma.ErrorReportSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ErrorReport
   */
  omit?: Prisma.ErrorReportOmit<ExtArgs> | null
}
