
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `EventPlayer` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model EventPlayer
 * 
 */
export type EventPlayerModel = runtime.Types.Result.DefaultSelection<Prisma.$EventPlayerPayload>

export type AggregateEventPlayer = {
  _count: EventPlayerCountAggregateOutputType | null
  _avg: EventPlayerAvgAggregateOutputType | null
  _sum: EventPlayerSumAggregateOutputType | null
  _min: EventPlayerMinAggregateOutputType | null
  _max: EventPlayerMaxAggregateOutputType | null
}

export type EventPlayerAvgAggregateOutputType = {
  fee: number | null
}

export type EventPlayerSumAggregateOutputType = {
  fee: number | null
}

export type EventPlayerMinAggregateOutputType = {
  id: string | null
  eventId: string | null
  playerId: string | null
  fee: number | null
  role: string | null
  paymentDueDate: Date | null
  paymentStatus: $Enums.PaymentStatus | null
  notes: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type EventPlayerMaxAggregateOutputType = {
  id: string | null
  eventId: string | null
  playerId: string | null
  fee: number | null
  role: string | null
  paymentDueDate: Date | null
  paymentStatus: $Enums.PaymentStatus | null
  notes: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type EventPlayerCountAggregateOutputType = {
  id: number
  eventId: number
  playerId: number
  fee: number
  role: number
  paymentDueDate: number
  paymentStatus: number
  notes: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type EventPlayerAvgAggregateInputType = {
  fee?: true
}

export type EventPlayerSumAggregateInputType = {
  fee?: true
}

export type EventPlayerMinAggregateInputType = {
  id?: true
  eventId?: true
  playerId?: true
  fee?: true
  role?: true
  paymentDueDate?: true
  paymentStatus?: true
  notes?: true
  createdAt?: true
  updatedAt?: true
}

export type EventPlayerMaxAggregateInputType = {
  id?: true
  eventId?: true
  playerId?: true
  fee?: true
  role?: true
  paymentDueDate?: true
  paymentStatus?: true
  notes?: true
  createdAt?: true
  updatedAt?: true
}

export type EventPlayerCountAggregateInputType = {
  id?: true
  eventId?: true
  playerId?: true
  fee?: true
  role?: true
  paymentDueDate?: true
  paymentStatus?: true
  notes?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type EventPlayerAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which EventPlayer to aggregate.
   */
  where?: Prisma.EventPlayerWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of EventPlayers to fetch.
   */
  orderBy?: Prisma.EventPlayerOrderByWithRelationInput | Prisma.EventPlayerOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.EventPlayerWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` EventPlayers from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` EventPlayers.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned EventPlayers
  **/
  _count?: true | EventPlayerCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: EventPlayerAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: EventPlayerSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: EventPlayerMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: EventPlayerMaxAggregateInputType
}

export type GetEventPlayerAggregateType<T extends EventPlayerAggregateArgs> = {
      [P in keyof T & keyof AggregateEventPlayer]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateEventPlayer[P]>
    : Prisma.GetScalarType<T[P], AggregateEventPlayer[P]>
}




export type EventPlayerGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.EventPlayerWhereInput
  orderBy?: Prisma.EventPlayerOrderByWithAggregationInput | Prisma.EventPlayerOrderByWithAggregationInput[]
  by: Prisma.EventPlayerScalarFieldEnum[] | Prisma.EventPlayerScalarFieldEnum
  having?: Prisma.EventPlayerScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: EventPlayerCountAggregateInputType | true
  _avg?: EventPlayerAvgAggregateInputType
  _sum?: EventPlayerSumAggregateInputType
  _min?: EventPlayerMinAggregateInputType
  _max?: EventPlayerMaxAggregateInputType
}

export type EventPlayerGroupByOutputType = {
  id: string
  eventId: string
  playerId: string
  fee: number
  role: string | null
  paymentDueDate: Date | null
  paymentStatus: $Enums.PaymentStatus
  notes: string | null
  createdAt: Date
  updatedAt: Date
  _count: EventPlayerCountAggregateOutputType | null
  _avg: EventPlayerAvgAggregateOutputType | null
  _sum: EventPlayerSumAggregateOutputType | null
  _min: EventPlayerMinAggregateOutputType | null
  _max: EventPlayerMaxAggregateOutputType | null
}

type GetEventPlayerGroupByPayload<T extends EventPlayerGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<EventPlayerGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof EventPlayerGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], EventPlayerGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], EventPlayerGroupByOutputType[P]>
      }
    >
  >



export type EventPlayerWhereInput = {
  AND?: Prisma.EventPlayerWhereInput | Prisma.EventPlayerWhereInput[]
  OR?: Prisma.EventPlayerWhereInput[]
  NOT?: Prisma.EventPlayerWhereInput | Prisma.EventPlayerWhereInput[]
  id?: Prisma.StringFilter<"EventPlayer"> | string
  eventId?: Prisma.StringFilter<"EventPlayer"> | string
  playerId?: Prisma.StringFilter<"EventPlayer"> | string
  fee?: Prisma.FloatFilter<"EventPlayer"> | number
  role?: Prisma.StringNullableFilter<"EventPlayer"> | string | null
  paymentDueDate?: Prisma.DateTimeNullableFilter<"EventPlayer"> | Date | string | null
  paymentStatus?: Prisma.EnumPaymentStatusFilter<"EventPlayer"> | $Enums.PaymentStatus
  notes?: Prisma.StringNullableFilter<"EventPlayer"> | string | null
  createdAt?: Prisma.DateTimeFilter<"EventPlayer"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"EventPlayer"> | Date | string
  event?: Prisma.XOR<Prisma.EventScalarRelationFilter, Prisma.EventWhereInput>
  player?: Prisma.XOR<Prisma.PlayerScalarRelationFilter, Prisma.PlayerWhereInput>
  payments?: Prisma.PaymentListRelationFilter
}

export type EventPlayerOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  eventId?: Prisma.SortOrder
  playerId?: Prisma.SortOrder
  fee?: Prisma.SortOrder
  role?: Prisma.SortOrderInput | Prisma.SortOrder
  paymentDueDate?: Prisma.SortOrderInput | Prisma.SortOrder
  paymentStatus?: Prisma.SortOrder
  notes?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  event?: Prisma.EventOrderByWithRelationInput
  player?: Prisma.PlayerOrderByWithRelationInput
  payments?: Prisma.PaymentOrderByRelationAggregateInput
}

export type EventPlayerWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  eventId_playerId?: Prisma.EventPlayerEventIdPlayerIdCompoundUniqueInput
  AND?: Prisma.EventPlayerWhereInput | Prisma.EventPlayerWhereInput[]
  OR?: Prisma.EventPlayerWhereInput[]
  NOT?: Prisma.EventPlayerWhereInput | Prisma.EventPlayerWhereInput[]
  eventId?: Prisma.StringFilter<"EventPlayer"> | string
  playerId?: Prisma.StringFilter<"EventPlayer"> | string
  fee?: Prisma.FloatFilter<"EventPlayer"> | number
  role?: Prisma.StringNullableFilter<"EventPlayer"> | string | null
  paymentDueDate?: Prisma.DateTimeNullableFilter<"EventPlayer"> | Date | string | null
  paymentStatus?: Prisma.EnumPaymentStatusFilter<"EventPlayer"> | $Enums.PaymentStatus
  notes?: Prisma.StringNullableFilter<"EventPlayer"> | string | null
  createdAt?: Prisma.DateTimeFilter<"EventPlayer"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"EventPlayer"> | Date | string
  event?: Prisma.XOR<Prisma.EventScalarRelationFilter, Prisma.EventWhereInput>
  player?: Prisma.XOR<Prisma.PlayerScalarRelationFilter, Prisma.PlayerWhereInput>
  payments?: Prisma.PaymentListRelationFilter
}, "id" | "eventId_playerId">

export type EventPlayerOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  eventId?: Prisma.SortOrder
  playerId?: Prisma.SortOrder
  fee?: Prisma.SortOrder
  role?: Prisma.SortOrderInput | Prisma.SortOrder
  paymentDueDate?: Prisma.SortOrderInput | Prisma.SortOrder
  paymentStatus?: Prisma.SortOrder
  notes?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.EventPlayerCountOrderByAggregateInput
  _avg?: Prisma.EventPlayerAvgOrderByAggregateInput
  _max?: Prisma.EventPlayerMaxOrderByAggregateInput
  _min?: Prisma.EventPlayerMinOrderByAggregateInput
  _sum?: Prisma.EventPlayerSumOrderByAggregateInput
}

export type EventPlayerScalarWhereWithAggregatesInput = {
  AND?: Prisma.EventPlayerScalarWhereWithAggregatesInput | Prisma.EventPlayerScalarWhereWithAggregatesInput[]
  OR?: Prisma.EventPlayerScalarWhereWithAggregatesInput[]
  NOT?: Prisma.EventPlayerScalarWhereWithAggregatesInput | Prisma.EventPlayerScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"EventPlayer"> | string
  eventId?: Prisma.StringWithAggregatesFilter<"EventPlayer"> | string
  playerId?: Prisma.StringWithAggregatesFilter<"EventPlayer"> | string
  fee?: Prisma.FloatWithAggregatesFilter<"EventPlayer"> | number
  role?: Prisma.StringNullableWithAggregatesFilter<"EventPlayer"> | string | null
  paymentDueDate?: Prisma.DateTimeNullableWithAggregatesFilter<"EventPlayer"> | Date | string | null
  paymentStatus?: Prisma.EnumPaymentStatusWithAggregatesFilter<"EventPlayer"> | $Enums.PaymentStatus
  notes?: Prisma.StringNullableWithAggregatesFilter<"EventPlayer"> | string | null
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"EventPlayer"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"EventPlayer"> | Date | string
}

export type EventPlayerCreateInput = {
  id?: string
  fee: number
  role?: string | null
  paymentDueDate?: Date | string | null
  paymentStatus?: $Enums.PaymentStatus
  notes?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  event: Prisma.EventCreateNestedOneWithoutEventPlayersInput
  player: Prisma.PlayerCreateNestedOneWithoutEventPlayersInput
  payments?: Prisma.PaymentCreateNestedManyWithoutEventPlayerInput
}

export type EventPlayerUncheckedCreateInput = {
  id?: string
  eventId: string
  playerId: string
  fee: number
  role?: string | null
  paymentDueDate?: Date | string | null
  paymentStatus?: $Enums.PaymentStatus
  notes?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  payments?: Prisma.PaymentUncheckedCreateNestedManyWithoutEventPlayerInput
}

export type EventPlayerUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  fee?: Prisma.FloatFieldUpdateOperationsInput | number
  role?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  paymentDueDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  paymentStatus?: Prisma.EnumPaymentStatusFieldUpdateOperationsInput | $Enums.PaymentStatus
  notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  event?: Prisma.EventUpdateOneRequiredWithoutEventPlayersNestedInput
  player?: Prisma.PlayerUpdateOneRequiredWithoutEventPlayersNestedInput
  payments?: Prisma.PaymentUpdateManyWithoutEventPlayerNestedInput
}

export type EventPlayerUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  eventId?: Prisma.StringFieldUpdateOperationsInput | string
  playerId?: Prisma.StringFieldUpdateOperationsInput | string
  fee?: Prisma.FloatFieldUpdateOperationsInput | number
  role?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  paymentDueDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  paymentStatus?: Prisma.EnumPaymentStatusFieldUpdateOperationsInput | $Enums.PaymentStatus
  notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  payments?: Prisma.PaymentUncheckedUpdateManyWithoutEventPlayerNestedInput
}

export type EventPlayerCreateManyInput = {
  id?: string
  eventId: string
  playerId: string
  fee: number
  role?: string | null
  paymentDueDate?: Date | string | null
  paymentStatus?: $Enums.PaymentStatus
  notes?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type EventPlayerUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  fee?: Prisma.FloatFieldUpdateOperationsInput | number
  role?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  paymentDueDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  paymentStatus?: Prisma.EnumPaymentStatusFieldUpdateOperationsInput | $Enums.PaymentStatus
  notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type EventPlayerUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  eventId?: Prisma.StringFieldUpdateOperationsInput | string
  playerId?: Prisma.StringFieldUpdateOperationsInput | string
  fee?: Prisma.FloatFieldUpdateOperationsInput | number
  role?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  paymentDueDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  paymentStatus?: Prisma.EnumPaymentStatusFieldUpdateOperationsInput | $Enums.PaymentStatus
  notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type EventPlayerListRelationFilter = {
  every?: Prisma.EventPlayerWhereInput
  some?: Prisma.EventPlayerWhereInput
  none?: Prisma.EventPlayerWhereInput
}

export type EventPlayerOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type EventPlayerEventIdPlayerIdCompoundUniqueInput = {
  eventId: string
  playerId: string
}

export type EventPlayerCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  eventId?: Prisma.SortOrder
  playerId?: Prisma.SortOrder
  fee?: Prisma.SortOrder
  role?: Prisma.SortOrder
  paymentDueDate?: Prisma.SortOrder
  paymentStatus?: Prisma.SortOrder
  notes?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type EventPlayerAvgOrderByAggregateInput = {
  fee?: Prisma.SortOrder
}

export type EventPlayerMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  eventId?: Prisma.SortOrder
  playerId?: Prisma.SortOrder
  fee?: Prisma.SortOrder
  role?: Prisma.SortOrder
  paymentDueDate?: Prisma.SortOrder
  paymentStatus?: Prisma.SortOrder
  notes?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type EventPlayerMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  eventId?: Prisma.SortOrder
  playerId?: Prisma.SortOrder
  fee?: Prisma.SortOrder
  role?: Prisma.SortOrder
  paymentDueDate?: Prisma.SortOrder
  paymentStatus?: Prisma.SortOrder
  notes?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type EventPlayerSumOrderByAggregateInput = {
  fee?: Prisma.SortOrder
}

export type EventPlayerScalarRelationFilter = {
  is?: Prisma.EventPlayerWhereInput
  isNot?: Prisma.EventPlayerWhereInput
}

export type EventPlayerCreateNestedManyWithoutPlayerInput = {
  create?: Prisma.XOR<Prisma.EventPlayerCreateWithoutPlayerInput, Prisma.EventPlayerUncheckedCreateWithoutPlayerInput> | Prisma.EventPlayerCreateWithoutPlayerInput[] | Prisma.EventPlayerUncheckedCreateWithoutPlayerInput[]
  connectOrCreate?: Prisma.EventPlayerCreateOrConnectWithoutPlayerInput | Prisma.EventPlayerCreateOrConnectWithoutPlayerInput[]
  createMany?: Prisma.EventPlayerCreateManyPlayerInputEnvelope
  connect?: Prisma.EventPlayerWhereUniqueInput | Prisma.EventPlayerWhereUniqueInput[]
}

export type EventPlayerUncheckedCreateNestedManyWithoutPlayerInput = {
  create?: Prisma.XOR<Prisma.EventPlayerCreateWithoutPlayerInput, Prisma.EventPlayerUncheckedCreateWithoutPlayerInput> | Prisma.EventPlayerCreateWithoutPlayerInput[] | Prisma.EventPlayerUncheckedCreateWithoutPlayerInput[]
  connectOrCreate?: Prisma.EventPlayerCreateOrConnectWithoutPlayerInput | Prisma.EventPlayerCreateOrConnectWithoutPlayerInput[]
  createMany?: Prisma.EventPlayerCreateManyPlayerInputEnvelope
  connect?: Prisma.EventPlayerWhereUniqueInput | Prisma.EventPlayerWhereUniqueInput[]
}

export type EventPlayerUpdateManyWithoutPlayerNestedInput = {
  create?: Prisma.XOR<Prisma.EventPlayerCreateWithoutPlayerInput, Prisma.EventPlayerUncheckedCreateWithoutPlayerInput> | Prisma.EventPlayerCreateWithoutPlayerInput[] | Prisma.EventPlayerUncheckedCreateWithoutPlayerInput[]
  connectOrCreate?: Prisma.EventPlayerCreateOrConnectWithoutPlayerInput | Prisma.EventPlayerCreateOrConnectWithoutPlayerInput[]
  upsert?: Prisma.EventPlayerUpsertWithWhereUniqueWithoutPlayerInput | Prisma.EventPlayerUpsertWithWhereUniqueWithoutPlayerInput[]
  createMany?: Prisma.EventPlayerCreateManyPlayerInputEnvelope
  set?: Prisma.EventPlayerWhereUniqueInput | Prisma.EventPlayerWhereUniqueInput[]
  disconnect?: Prisma.EventPlayerWhereUniqueInput | Prisma.EventPlayerWhereUniqueInput[]
  delete?: Prisma.EventPlayerWhereUniqueInput | Prisma.EventPlayerWhereUniqueInput[]
  connect?: Prisma.EventPlayerWhereUniqueInput | Prisma.EventPlayerWhereUniqueInput[]
  update?: Prisma.EventPlayerUpdateWithWhereUniqueWithoutPlayerInput | Prisma.EventPlayerUpdateWithWhereUniqueWithoutPlayerInput[]
  updateMany?: Prisma.EventPlayerUpdateManyWithWhereWithoutPlayerInput | Prisma.EventPlayerUpdateManyWithWhereWithoutPlayerInput[]
  deleteMany?: Prisma.EventPlayerScalarWhereInput | Prisma.EventPlayerScalarWhereInput[]
}

export type EventPlayerUncheckedUpdateManyWithoutPlayerNestedInput = {
  create?: Prisma.XOR<Prisma.EventPlayerCreateWithoutPlayerInput, Prisma.EventPlayerUncheckedCreateWithoutPlayerInput> | Prisma.EventPlayerCreateWithoutPlayerInput[] | Prisma.EventPlayerUncheckedCreateWithoutPlayerInput[]
  connectOrCreate?: Prisma.EventPlayerCreateOrConnectWithoutPlayerInput | Prisma.EventPlayerCreateOrConnectWithoutPlayerInput[]
  upsert?: Prisma.EventPlayerUpsertWithWhereUniqueWithoutPlayerInput | Prisma.EventPlayerUpsertWithWhereUniqueWithoutPlayerInput[]
  createMany?: Prisma.EventPlayerCreateManyPlayerInputEnvelope
  set?: Prisma.EventPlayerWhereUniqueInput | Prisma.EventPlayerWhereUniqueInput[]
  disconnect?: Prisma.EventPlayerWhereUniqueInput | Prisma.EventPlayerWhereUniqueInput[]
  delete?: Prisma.EventPlayerWhereUniqueInput | Prisma.EventPlayerWhereUniqueInput[]
  connect?: Prisma.EventPlayerWhereUniqueInput | Prisma.EventPlayerWhereUniqueInput[]
  update?: Prisma.EventPlayerUpdateWithWhereUniqueWithoutPlayerInput | Prisma.EventPlayerUpdateWithWhereUniqueWithoutPlayerInput[]
  updateMany?: Prisma.EventPlayerUpdateManyWithWhereWithoutPlayerInput | Prisma.EventPlayerUpdateManyWithWhereWithoutPlayerInput[]
  deleteMany?: Prisma.EventPlayerScalarWhereInput | Prisma.EventPlayerScalarWhereInput[]
}

export type EventPlayerCreateNestedManyWithoutEventInput = {
  create?: Prisma.XOR<Prisma.EventPlayerCreateWithoutEventInput, Prisma.EventPlayerUncheckedCreateWithoutEventInput> | Prisma.EventPlayerCreateWithoutEventInput[] | Prisma.EventPlayerUncheckedCreateWithoutEventInput[]
  connectOrCreate?: Prisma.EventPlayerCreateOrConnectWithoutEventInput | Prisma.EventPlayerCreateOrConnectWithoutEventInput[]
  createMany?: Prisma.EventPlayerCreateManyEventInputEnvelope
  connect?: Prisma.EventPlayerWhereUniqueInput | Prisma.EventPlayerWhereUniqueInput[]
}

export type EventPlayerUncheckedCreateNestedManyWithoutEventInput = {
  create?: Prisma.XOR<Prisma.EventPlayerCreateWithoutEventInput, Prisma.EventPlayerUncheckedCreateWithoutEventInput> | Prisma.EventPlayerCreateWithoutEventInput[] | Prisma.EventPlayerUncheckedCreateWithoutEventInput[]
  connectOrCreate?: Prisma.EventPlayerCreateOrConnectWithoutEventInput | Prisma.EventPlayerCreateOrConnectWithoutEventInput[]
  createMany?: Prisma.EventPlayerCreateManyEventInputEnvelope
  connect?: Prisma.EventPlayerWhereUniqueInput | Prisma.EventPlayerWhereUniqueInput[]
}

export type EventPlayerUpdateManyWithoutEventNestedInput = {
  create?: Prisma.XOR<Prisma.EventPlayerCreateWithoutEventInput, Prisma.EventPlayerUncheckedCreateWithoutEventInput> | Prisma.EventPlayerCreateWithoutEventInput[] | Prisma.EventPlayerUncheckedCreateWithoutEventInput[]
  connectOrCreate?: Prisma.EventPlayerCreateOrConnectWithoutEventInput | Prisma.EventPlayerCreateOrConnectWithoutEventInput[]
  upsert?: Prisma.EventPlayerUpsertWithWhereUniqueWithoutEventInput | Prisma.EventPlayerUpsertWithWhereUniqueWithoutEventInput[]
  createMany?: Prisma.EventPlayerCreateManyEventInputEnvelope
  set?: Prisma.EventPlayerWhereUniqueInput | Prisma.EventPlayerWhereUniqueInput[]
  disconnect?: Prisma.EventPlayerWhereUniqueInput | Prisma.EventPlayerWhereUniqueInput[]
  delete?: Prisma.EventPlayerWhereUniqueInput | Prisma.EventPlayerWhereUniqueInput[]
  connect?: Prisma.EventPlayerWhereUniqueInput | Prisma.EventPlayerWhereUniqueInput[]
  update?: Prisma.EventPlayerUpdateWithWhereUniqueWithoutEventInput | Prisma.EventPlayerUpdateWithWhereUniqueWithoutEventInput[]
  updateMany?: Prisma.EventPlayerUpdateManyWithWhereWithoutEventInput | Prisma.EventPlayerUpdateManyWithWhereWithoutEventInput[]
  deleteMany?: Prisma.EventPlayerScalarWhereInput | Prisma.EventPlayerScalarWhereInput[]
}

export type EventPlayerUncheckedUpdateManyWithoutEventNestedInput = {
  create?: Prisma.XOR<Prisma.EventPlayerCreateWithoutEventInput, Prisma.EventPlayerUncheckedCreateWithoutEventInput> | Prisma.EventPlayerCreateWithoutEventInput[] | Prisma.EventPlayerUncheckedCreateWithoutEventInput[]
  connectOrCreate?: Prisma.EventPlayerCreateOrConnectWithoutEventInput | Prisma.EventPlayerCreateOrConnectWithoutEventInput[]
  upsert?: Prisma.EventPlayerUpsertWithWhereUniqueWithoutEventInput | Prisma.EventPlayerUpsertWithWhereUniqueWithoutEventInput[]
  createMany?: Prisma.EventPlayerCreateManyEventInputEnvelope
  set?: Prisma.EventPlayerWhereUniqueInput | Prisma.EventPlayerWhereUniqueInput[]
  disconnect?: Prisma.EventPlayerWhereUniqueInput | Prisma.EventPlayerWhereUniqueInput[]
  delete?: Prisma.EventPlayerWhereUniqueInput | Prisma.EventPlayerWhereUniqueInput[]
  connect?: Prisma.EventPlayerWhereUniqueInput | Prisma.EventPlayerWhereUniqueInput[]
  update?: Prisma.EventPlayerUpdateWithWhereUniqueWithoutEventInput | Prisma.EventPlayerUpdateWithWhereUniqueWithoutEventInput[]
  updateMany?: Prisma.EventPlayerUpdateManyWithWhereWithoutEventInput | Prisma.EventPlayerUpdateManyWithWhereWithoutEventInput[]
  deleteMany?: Prisma.EventPlayerScalarWhereInput | Prisma.EventPlayerScalarWhereInput[]
}

export type FloatFieldUpdateOperationsInput = {
  set?: number
  increment?: number
  decrement?: number
  multiply?: number
  divide?: number
}

export type NullableDateTimeFieldUpdateOperationsInput = {
  set?: Date | string | null
}

export type EnumPaymentStatusFieldUpdateOperationsInput = {
  set?: $Enums.PaymentStatus
}

export type EventPlayerCreateNestedOneWithoutPaymentsInput = {
  create?: Prisma.XOR<Prisma.EventPlayerCreateWithoutPaymentsInput, Prisma.EventPlayerUncheckedCreateWithoutPaymentsInput>
  connectOrCreate?: Prisma.EventPlayerCreateOrConnectWithoutPaymentsInput
  connect?: Prisma.EventPlayerWhereUniqueInput
}

export type EventPlayerUpdateOneRequiredWithoutPaymentsNestedInput = {
  create?: Prisma.XOR<Prisma.EventPlayerCreateWithoutPaymentsInput, Prisma.EventPlayerUncheckedCreateWithoutPaymentsInput>
  connectOrCreate?: Prisma.EventPlayerCreateOrConnectWithoutPaymentsInput
  upsert?: Prisma.EventPlayerUpsertWithoutPaymentsInput
  connect?: Prisma.EventPlayerWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.EventPlayerUpdateToOneWithWhereWithoutPaymentsInput, Prisma.EventPlayerUpdateWithoutPaymentsInput>, Prisma.EventPlayerUncheckedUpdateWithoutPaymentsInput>
}

export type EventPlayerCreateWithoutPlayerInput = {
  id?: string
  fee: number
  role?: string | null
  paymentDueDate?: Date | string | null
  paymentStatus?: $Enums.PaymentStatus
  notes?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  event: Prisma.EventCreateNestedOneWithoutEventPlayersInput
  payments?: Prisma.PaymentCreateNestedManyWithoutEventPlayerInput
}

export type EventPlayerUncheckedCreateWithoutPlayerInput = {
  id?: string
  eventId: string
  fee: number
  role?: string | null
  paymentDueDate?: Date | string | null
  paymentStatus?: $Enums.PaymentStatus
  notes?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  payments?: Prisma.PaymentUncheckedCreateNestedManyWithoutEventPlayerInput
}

export type EventPlayerCreateOrConnectWithoutPlayerInput = {
  where: Prisma.EventPlayerWhereUniqueInput
  create: Prisma.XOR<Prisma.EventPlayerCreateWithoutPlayerInput, Prisma.EventPlayerUncheckedCreateWithoutPlayerInput>
}

export type EventPlayerCreateManyPlayerInputEnvelope = {
  data: Prisma.EventPlayerCreateManyPlayerInput | Prisma.EventPlayerCreateManyPlayerInput[]
}

export type EventPlayerUpsertWithWhereUniqueWithoutPlayerInput = {
  where: Prisma.EventPlayerWhereUniqueInput
  update: Prisma.XOR<Prisma.EventPlayerUpdateWithoutPlayerInput, Prisma.EventPlayerUncheckedUpdateWithoutPlayerInput>
  create: Prisma.XOR<Prisma.EventPlayerCreateWithoutPlayerInput, Prisma.EventPlayerUncheckedCreateWithoutPlayerInput>
}

export type EventPlayerUpdateWithWhereUniqueWithoutPlayerInput = {
  where: Prisma.EventPlayerWhereUniqueInput
  data: Prisma.XOR<Prisma.EventPlayerUpdateWithoutPlayerInput, Prisma.EventPlayerUncheckedUpdateWithoutPlayerInput>
}

export type EventPlayerUpdateManyWithWhereWithoutPlayerInput = {
  where: Prisma.EventPlayerScalarWhereInput
  data: Prisma.XOR<Prisma.EventPlayerUpdateManyMutationInput, Prisma.EventPlayerUncheckedUpdateManyWithoutPlayerInput>
}

export type EventPlayerScalarWhereInput = {
  AND?: Prisma.EventPlayerScalarWhereInput | Prisma.EventPlayerScalarWhereInput[]
  OR?: Prisma.EventPlayerScalarWhereInput[]
  NOT?: Prisma.EventPlayerScalarWhereInput | Prisma.EventPlayerScalarWhereInput[]
  id?: Prisma.StringFilter<"EventPlayer"> | string
  eventId?: Prisma.StringFilter<"EventPlayer"> | string
  playerId?: Prisma.StringFilter<"EventPlayer"> | string
  fee?: Prisma.FloatFilter<"EventPlayer"> | number
  role?: Prisma.StringNullableFilter<"EventPlayer"> | string | null
  paymentDueDate?: Prisma.DateTimeNullableFilter<"EventPlayer"> | Date | string | null
  paymentStatus?: Prisma.EnumPaymentStatusFilter<"EventPlayer"> | $Enums.PaymentStatus
  notes?: Prisma.StringNullableFilter<"EventPlayer"> | string | null
  createdAt?: Prisma.DateTimeFilter<"EventPlayer"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"EventPlayer"> | Date | string
}

export type EventPlayerCreateWithoutEventInput = {
  id?: string
  fee: number
  role?: string | null
  paymentDueDate?: Date | string | null
  paymentStatus?: $Enums.PaymentStatus
  notes?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  player: Prisma.PlayerCreateNestedOneWithoutEventPlayersInput
  payments?: Prisma.PaymentCreateNestedManyWithoutEventPlayerInput
}

export type EventPlayerUncheckedCreateWithoutEventInput = {
  id?: string
  playerId: string
  fee: number
  role?: string | null
  paymentDueDate?: Date | string | null
  paymentStatus?: $Enums.PaymentStatus
  notes?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  payments?: Prisma.PaymentUncheckedCreateNestedManyWithoutEventPlayerInput
}

export type EventPlayerCreateOrConnectWithoutEventInput = {
  where: Prisma.EventPlayerWhereUniqueInput
  create: Prisma.XOR<Prisma.EventPlayerCreateWithoutEventInput, Prisma.EventPlayerUncheckedCreateWithoutEventInput>
}

export type EventPlayerCreateManyEventInputEnvelope = {
  data: Prisma.EventPlayerCreateManyEventInput | Prisma.EventPlayerCreateManyEventInput[]
}

export type EventPlayerUpsertWithWhereUniqueWithoutEventInput = {
  where: Prisma.EventPlayerWhereUniqueInput
  update: Prisma.XOR<Prisma.EventPlayerUpdateWithoutEventInput, Prisma.EventPlayerUncheckedUpdateWithoutEventInput>
  create: Prisma.XOR<Prisma.EventPlayerCreateWithoutEventInput, Prisma.EventPlayerUncheckedCreateWithoutEventInput>
}

export type EventPlayerUpdateWithWhereUniqueWithoutEventInput = {
  where: Prisma.EventPlayerWhereUniqueInput
  data: Prisma.XOR<Prisma.EventPlayerUpdateWithoutEventInput, Prisma.EventPlayerUncheckedUpdateWithoutEventInput>
}

export type EventPlayerUpdateManyWithWhereWithoutEventInput = {
  where: Prisma.EventPlayerScalarWhereInput
  data: Prisma.XOR<Prisma.EventPlayerUpdateManyMutationInput, Prisma.EventPlayerUncheckedUpdateManyWithoutEventInput>
}

export type EventPlayerCreateWithoutPaymentsInput = {
  id?: string
  fee: number
  role?: string | null
  paymentDueDate?: Date | string | null
  paymentStatus?: $Enums.PaymentStatus
  notes?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  event: Prisma.EventCreateNestedOneWithoutEventPlayersInput
  player: Prisma.PlayerCreateNestedOneWithoutEventPlayersInput
}

export type EventPlayerUncheckedCreateWithoutPaymentsInput = {
  id?: string
  eventId: string
  playerId: string
  fee: number
  role?: string | null
  paymentDueDate?: Date | string | null
  paymentStatus?: $Enums.PaymentStatus
  notes?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type EventPlayerCreateOrConnectWithoutPaymentsInput = {
  where: Prisma.EventPlayerWhereUniqueInput
  create: Prisma.XOR<Prisma.EventPlayerCreateWithoutPaymentsInput, Prisma.EventPlayerUncheckedCreateWithoutPaymentsInput>
}

export type EventPlayerUpsertWithoutPaymentsInput = {
  update: Prisma.XOR<Prisma.EventPlayerUpdateWithoutPaymentsInput, Prisma.EventPlayerUncheckedUpdateWithoutPaymentsInput>
  create: Prisma.XOR<Prisma.EventPlayerCreateWithoutPaymentsInput, Prisma.EventPlayerUncheckedCreateWithoutPaymentsInput>
  where?: Prisma.EventPlayerWhereInput
}

export type EventPlayerUpdateToOneWithWhereWithoutPaymentsInput = {
  where?: Prisma.EventPlayerWhereInput
  data: Prisma.XOR<Prisma.EventPlayerUpdateWithoutPaymentsInput, Prisma.EventPlayerUncheckedUpdateWithoutPaymentsInput>
}

export type EventPlayerUpdateWithoutPaymentsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  fee?: Prisma.FloatFieldUpdateOperationsInput | number
  role?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  paymentDueDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  paymentStatus?: Prisma.EnumPaymentStatusFieldUpdateOperationsInput | $Enums.PaymentStatus
  notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  event?: Prisma.EventUpdateOneRequiredWithoutEventPlayersNestedInput
  player?: Prisma.PlayerUpdateOneRequiredWithoutEventPlayersNestedInput
}

export type EventPlayerUncheckedUpdateWithoutPaymentsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  eventId?: Prisma.StringFieldUpdateOperationsInput | string
  playerId?: Prisma.StringFieldUpdateOperationsInput | string
  fee?: Prisma.FloatFieldUpdateOperationsInput | number
  role?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  paymentDueDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  paymentStatus?: Prisma.EnumPaymentStatusFieldUpdateOperationsInput | $Enums.PaymentStatus
  notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type EventPlayerCreateManyPlayerInput = {
  id?: string
  eventId: string
  fee: number
  role?: string | null
  paymentDueDate?: Date | string | null
  paymentStatus?: $Enums.PaymentStatus
  notes?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type EventPlayerUpdateWithoutPlayerInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  fee?: Prisma.FloatFieldUpdateOperationsInput | number
  role?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  paymentDueDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  paymentStatus?: Prisma.EnumPaymentStatusFieldUpdateOperationsInput | $Enums.PaymentStatus
  notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  event?: Prisma.EventUpdateOneRequiredWithoutEventPlayersNestedInput
  payments?: Prisma.PaymentUpdateManyWithoutEventPlayerNestedInput
}

export type EventPlayerUncheckedUpdateWithoutPlayerInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  eventId?: Prisma.StringFieldUpdateOperationsInput | string
  fee?: Prisma.FloatFieldUpdateOperationsInput | number
  role?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  paymentDueDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  paymentStatus?: Prisma.EnumPaymentStatusFieldUpdateOperationsInput | $Enums.PaymentStatus
  notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  payments?: Prisma.PaymentUncheckedUpdateManyWithoutEventPlayerNestedInput
}

export type EventPlayerUncheckedUpdateManyWithoutPlayerInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  eventId?: Prisma.StringFieldUpdateOperationsInput | string
  fee?: Prisma.FloatFieldUpdateOperationsInput | number
  role?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  paymentDueDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  paymentStatus?: Prisma.EnumPaymentStatusFieldUpdateOperationsInput | $Enums.PaymentStatus
  notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type EventPlayerCreateManyEventInput = {
  id?: string
  playerId: string
  fee: number
  role?: string | null
  paymentDueDate?: Date | string | null
  paymentStatus?: $Enums.PaymentStatus
  notes?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type EventPlayerUpdateWithoutEventInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  fee?: Prisma.FloatFieldUpdateOperationsInput | number
  role?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  paymentDueDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  paymentStatus?: Prisma.EnumPaymentStatusFieldUpdateOperationsInput | $Enums.PaymentStatus
  notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  player?: Prisma.PlayerUpdateOneRequiredWithoutEventPlayersNestedInput
  payments?: Prisma.PaymentUpdateManyWithoutEventPlayerNestedInput
}

export type EventPlayerUncheckedUpdateWithoutEventInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  playerId?: Prisma.StringFieldUpdateOperationsInput | string
  fee?: Prisma.FloatFieldUpdateOperationsInput | number
  role?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  paymentDueDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  paymentStatus?: Prisma.EnumPaymentStatusFieldUpdateOperationsInput | $Enums.PaymentStatus
  notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  payments?: Prisma.PaymentUncheckedUpdateManyWithoutEventPlayerNestedInput
}

export type EventPlayerUncheckedUpdateManyWithoutEventInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  playerId?: Prisma.StringFieldUpdateOperationsInput | string
  fee?: Prisma.FloatFieldUpdateOperationsInput | number
  role?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  paymentDueDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  paymentStatus?: Prisma.EnumPaymentStatusFieldUpdateOperationsInput | $Enums.PaymentStatus
  notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}


/**
 * Count Type EventPlayerCountOutputType
 */

export type EventPlayerCountOutputType = {
  payments: number
}

export type EventPlayerCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  payments?: boolean | EventPlayerCountOutputTypeCountPaymentsArgs
}

/**
 * EventPlayerCountOutputType without action
 */
export type EventPlayerCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the EventPlayerCountOutputType
   */
  select?: Prisma.EventPlayerCountOutputTypeSelect<ExtArgs> | null
}

/**
 * EventPlayerCountOutputType without action
 */
export type EventPlayerCountOutputTypeCountPaymentsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.PaymentWhereInput
}


export type EventPlayerSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  eventId?: boolean
  playerId?: boolean
  fee?: boolean
  role?: boolean
  paymentDueDate?: boolean
  paymentStatus?: boolean
  notes?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  event?: boolean | Prisma.EventDefaultArgs<ExtArgs>
  player?: boolean | Prisma.PlayerDefaultArgs<ExtArgs>
  payments?: boolean | Prisma.EventPlayer$paymentsArgs<ExtArgs>
  _count?: boolean | Prisma.EventPlayerCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["eventPlayer"]>

export type EventPlayerSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  eventId?: boolean
  playerId?: boolean
  fee?: boolean
  role?: boolean
  paymentDueDate?: boolean
  paymentStatus?: boolean
  notes?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  event?: boolean | Prisma.EventDefaultArgs<ExtArgs>
  player?: boolean | Prisma.PlayerDefaultArgs<ExtArgs>
}, ExtArgs["result"]["eventPlayer"]>

export type EventPlayerSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  eventId?: boolean
  playerId?: boolean
  fee?: boolean
  role?: boolean
  paymentDueDate?: boolean
  paymentStatus?: boolean
  notes?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  event?: boolean | Prisma.EventDefaultArgs<ExtArgs>
  player?: boolean | Prisma.PlayerDefaultArgs<ExtArgs>
}, ExtArgs["result"]["eventPlayer"]>

export type EventPlayerSelectScalar = {
  id?: boolean
  eventId?: boolean
  playerId?: boolean
  fee?: boolean
  role?: boolean
  paymentDueDate?: boolean
  paymentStatus?: boolean
  notes?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type EventPlayerOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "eventId" | "playerId" | "fee" | "role" | "paymentDueDate" | "paymentStatus" | "notes" | "createdAt" | "updatedAt", ExtArgs["result"]["eventPlayer"]>
export type EventPlayerInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  event?: boolean | Prisma.EventDefaultArgs<ExtArgs>
  player?: boolean | Prisma.PlayerDefaultArgs<ExtArgs>
  payments?: boolean | Prisma.EventPlayer$paymentsArgs<ExtArgs>
  _count?: boolean | Prisma.EventPlayerCountOutputTypeDefaultArgs<ExtArgs>
}
export type EventPlayerIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  event?: boolean | Prisma.EventDefaultArgs<ExtArgs>
  player?: boolean | Prisma.PlayerDefaultArgs<ExtArgs>
}
export type EventPlayerIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  event?: boolean | Prisma.EventDefaultArgs<ExtArgs>
  player?: boolean | Prisma.PlayerDefaultArgs<ExtArgs>
}

export type $EventPlayerPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "EventPlayer"
  objects: {
    event: Prisma.$EventPayload<ExtArgs>
    player: Prisma.$PlayerPayload<ExtArgs>
    payments: Prisma.$PaymentPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    eventId: string
    playerId: string
    fee: number
    role: string | null
    paymentDueDate: Date | null
    paymentStatus: $Enums.PaymentStatus
    notes: string | null
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["eventPlayer"]>
  composites: {}
}

export type EventPlayerGetPayload<S extends boolean | null | undefined | EventPlayerDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$EventPlayerPayload, S>

export type EventPlayerCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<EventPlayerFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: EventPlayerCountAggregateInputType | true
  }

export interface EventPlayerDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['EventPlayer'], meta: { name: 'EventPlayer' } }
  /**
   * Find zero or one EventPlayer that matches the filter.
   * @param {EventPlayerFindUniqueArgs} args - Arguments to find a EventPlayer
   * @example
   * // Get one EventPlayer
   * const eventPlayer = await prisma.eventPlayer.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends EventPlayerFindUniqueArgs>(args: Prisma.SelectSubset<T, EventPlayerFindUniqueArgs<ExtArgs>>): Prisma.Prisma__EventPlayerClient<runtime.Types.Result.GetResult<Prisma.$EventPlayerPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one EventPlayer that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {EventPlayerFindUniqueOrThrowArgs} args - Arguments to find a EventPlayer
   * @example
   * // Get one EventPlayer
   * const eventPlayer = await prisma.eventPlayer.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends EventPlayerFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, EventPlayerFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__EventPlayerClient<runtime.Types.Result.GetResult<Prisma.$EventPlayerPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first EventPlayer that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {EventPlayerFindFirstArgs} args - Arguments to find a EventPlayer
   * @example
   * // Get one EventPlayer
   * const eventPlayer = await prisma.eventPlayer.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends EventPlayerFindFirstArgs>(args?: Prisma.SelectSubset<T, EventPlayerFindFirstArgs<ExtArgs>>): Prisma.Prisma__EventPlayerClient<runtime.Types.Result.GetResult<Prisma.$EventPlayerPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first EventPlayer that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {EventPlayerFindFirstOrThrowArgs} args - Arguments to find a EventPlayer
   * @example
   * // Get one EventPlayer
   * const eventPlayer = await prisma.eventPlayer.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends EventPlayerFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, EventPlayerFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__EventPlayerClient<runtime.Types.Result.GetResult<Prisma.$EventPlayerPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more EventPlayers that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {EventPlayerFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all EventPlayers
   * const eventPlayers = await prisma.eventPlayer.findMany()
   * 
   * // Get first 10 EventPlayers
   * const eventPlayers = await prisma.eventPlayer.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const eventPlayerWithIdOnly = await prisma.eventPlayer.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends EventPlayerFindManyArgs>(args?: Prisma.SelectSubset<T, EventPlayerFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$EventPlayerPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a EventPlayer.
   * @param {EventPlayerCreateArgs} args - Arguments to create a EventPlayer.
   * @example
   * // Create one EventPlayer
   * const EventPlayer = await prisma.eventPlayer.create({
   *   data: {
   *     // ... data to create a EventPlayer
   *   }
   * })
   * 
   */
  create<T extends EventPlayerCreateArgs>(args: Prisma.SelectSubset<T, EventPlayerCreateArgs<ExtArgs>>): Prisma.Prisma__EventPlayerClient<runtime.Types.Result.GetResult<Prisma.$EventPlayerPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many EventPlayers.
   * @param {EventPlayerCreateManyArgs} args - Arguments to create many EventPlayers.
   * @example
   * // Create many EventPlayers
   * const eventPlayer = await prisma.eventPlayer.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends EventPlayerCreateManyArgs>(args?: Prisma.SelectSubset<T, EventPlayerCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many EventPlayers and returns the data saved in the database.
   * @param {EventPlayerCreateManyAndReturnArgs} args - Arguments to create many EventPlayers.
   * @example
   * // Create many EventPlayers
   * const eventPlayer = await prisma.eventPlayer.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many EventPlayers and only return the `id`
   * const eventPlayerWithIdOnly = await prisma.eventPlayer.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends EventPlayerCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, EventPlayerCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$EventPlayerPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a EventPlayer.
   * @param {EventPlayerDeleteArgs} args - Arguments to delete one EventPlayer.
   * @example
   * // Delete one EventPlayer
   * const EventPlayer = await prisma.eventPlayer.delete({
   *   where: {
   *     // ... filter to delete one EventPlayer
   *   }
   * })
   * 
   */
  delete<T extends EventPlayerDeleteArgs>(args: Prisma.SelectSubset<T, EventPlayerDeleteArgs<ExtArgs>>): Prisma.Prisma__EventPlayerClient<runtime.Types.Result.GetResult<Prisma.$EventPlayerPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one EventPlayer.
   * @param {EventPlayerUpdateArgs} args - Arguments to update one EventPlayer.
   * @example
   * // Update one EventPlayer
   * const eventPlayer = await prisma.eventPlayer.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends EventPlayerUpdateArgs>(args: Prisma.SelectSubset<T, EventPlayerUpdateArgs<ExtArgs>>): Prisma.Prisma__EventPlayerClient<runtime.Types.Result.GetResult<Prisma.$EventPlayerPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more EventPlayers.
   * @param {EventPlayerDeleteManyArgs} args - Arguments to filter EventPlayers to delete.
   * @example
   * // Delete a few EventPlayers
   * const { count } = await prisma.eventPlayer.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends EventPlayerDeleteManyArgs>(args?: Prisma.SelectSubset<T, EventPlayerDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more EventPlayers.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {EventPlayerUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many EventPlayers
   * const eventPlayer = await prisma.eventPlayer.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends EventPlayerUpdateManyArgs>(args: Prisma.SelectSubset<T, EventPlayerUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more EventPlayers and returns the data updated in the database.
   * @param {EventPlayerUpdateManyAndReturnArgs} args - Arguments to update many EventPlayers.
   * @example
   * // Update many EventPlayers
   * const eventPlayer = await prisma.eventPlayer.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more EventPlayers and only return the `id`
   * const eventPlayerWithIdOnly = await prisma.eventPlayer.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends EventPlayerUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, EventPlayerUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$EventPlayerPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one EventPlayer.
   * @param {EventPlayerUpsertArgs} args - Arguments to update or create a EventPlayer.
   * @example
   * // Update or create a EventPlayer
   * const eventPlayer = await prisma.eventPlayer.upsert({
   *   create: {
   *     // ... data to create a EventPlayer
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the EventPlayer we want to update
   *   }
   * })
   */
  upsert<T extends EventPlayerUpsertArgs>(args: Prisma.SelectSubset<T, EventPlayerUpsertArgs<ExtArgs>>): Prisma.Prisma__EventPlayerClient<runtime.Types.Result.GetResult<Prisma.$EventPlayerPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of EventPlayers.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {EventPlayerCountArgs} args - Arguments to filter EventPlayers to count.
   * @example
   * // Count the number of EventPlayers
   * const count = await prisma.eventPlayer.count({
   *   where: {
   *     // ... the filter for the EventPlayers we want to count
   *   }
   * })
  **/
  count<T extends EventPlayerCountArgs>(
    args?: Prisma.Subset<T, EventPlayerCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], EventPlayerCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a EventPlayer.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {EventPlayerAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends EventPlayerAggregateArgs>(args: Prisma.Subset<T, EventPlayerAggregateArgs>): Prisma.PrismaPromise<GetEventPlayerAggregateType<T>>

  /**
   * Group by EventPlayer.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {EventPlayerGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends EventPlayerGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: EventPlayerGroupByArgs['orderBy'] }
      : { orderBy?: EventPlayerGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, EventPlayerGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetEventPlayerGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the EventPlayer model
 */
readonly fields: EventPlayerFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for EventPlayer.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__EventPlayerClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  event<T extends Prisma.EventDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.EventDefaultArgs<ExtArgs>>): Prisma.Prisma__EventClient<runtime.Types.Result.GetResult<Prisma.$EventPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  player<T extends Prisma.PlayerDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.PlayerDefaultArgs<ExtArgs>>): Prisma.Prisma__PlayerClient<runtime.Types.Result.GetResult<Prisma.$PlayerPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  payments<T extends Prisma.EventPlayer$paymentsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.EventPlayer$paymentsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PaymentPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the EventPlayer model
 */
export interface EventPlayerFieldRefs {
  readonly id: Prisma.FieldRef<"EventPlayer", 'String'>
  readonly eventId: Prisma.FieldRef<"EventPlayer", 'String'>
  readonly playerId: Prisma.FieldRef<"EventPlayer", 'String'>
  readonly fee: Prisma.FieldRef<"EventPlayer", 'Float'>
  readonly role: Prisma.FieldRef<"EventPlayer", 'String'>
  readonly paymentDueDate: Prisma.FieldRef<"EventPlayer", 'DateTime'>
  readonly paymentStatus: Prisma.FieldRef<"EventPlayer", 'PaymentStatus'>
  readonly notes: Prisma.FieldRef<"EventPlayer", 'String'>
  readonly createdAt: Prisma.FieldRef<"EventPlayer", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"EventPlayer", 'DateTime'>
}
    

// Custom InputTypes
/**
 * EventPlayer findUnique
 */
export type EventPlayerFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the EventPlayer
   */
  select?: Prisma.EventPlayerSelect<ExtArgs> | null
  /**
   * Omit specific fields from the EventPlayer
   */
  omit?: Prisma.EventPlayerOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EventPlayerInclude<ExtArgs> | null
  /**
   * Filter, which EventPlayer to fetch.
   */
  where: Prisma.EventPlayerWhereUniqueInput
}

/**
 * EventPlayer findUniqueOrThrow
 */
export type EventPlayerFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the EventPlayer
   */
  select?: Prisma.EventPlayerSelect<ExtArgs> | null
  /**
   * Omit specific fields from the EventPlayer
   */
  omit?: Prisma.EventPlayerOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EventPlayerInclude<ExtArgs> | null
  /**
   * Filter, which EventPlayer to fetch.
   */
  where: Prisma.EventPlayerWhereUniqueInput
}

/**
 * EventPlayer findFirst
 */
export type EventPlayerFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the EventPlayer
   */
  select?: Prisma.EventPlayerSelect<ExtArgs> | null
  /**
   * Omit specific fields from the EventPlayer
   */
  omit?: Prisma.EventPlayerOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EventPlayerInclude<ExtArgs> | null
  /**
   * Filter, which EventPlayer to fetch.
   */
  where?: Prisma.EventPlayerWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of EventPlayers to fetch.
   */
  orderBy?: Prisma.EventPlayerOrderByWithRelationInput | Prisma.EventPlayerOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for EventPlayers.
   */
  cursor?: Prisma.EventPlayerWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` EventPlayers from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` EventPlayers.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of EventPlayers.
   */
  distinct?: Prisma.EventPlayerScalarFieldEnum | Prisma.EventPlayerScalarFieldEnum[]
}

/**
 * EventPlayer findFirstOrThrow
 */
export type EventPlayerFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the EventPlayer
   */
  select?: Prisma.EventPlayerSelect<ExtArgs> | null
  /**
   * Omit specific fields from the EventPlayer
   */
  omit?: Prisma.EventPlayerOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EventPlayerInclude<ExtArgs> | null
  /**
   * Filter, which EventPlayer to fetch.
   */
  where?: Prisma.EventPlayerWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of EventPlayers to fetch.
   */
  orderBy?: Prisma.EventPlayerOrderByWithRelationInput | Prisma.EventPlayerOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for EventPlayers.
   */
  cursor?: Prisma.EventPlayerWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` EventPlayers from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` EventPlayers.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of EventPlayers.
   */
  distinct?: Prisma.EventPlayerScalarFieldEnum | Prisma.EventPlayerScalarFieldEnum[]
}

/**
 * EventPlayer findMany
 */
export type EventPlayerFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the EventPlayer
   */
  select?: Prisma.EventPlayerSelect<ExtArgs> | null
  /**
   * Omit specific fields from the EventPlayer
   */
  omit?: Prisma.EventPlayerOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EventPlayerInclude<ExtArgs> | null
  /**
   * Filter, which EventPlayers to fetch.
   */
  where?: Prisma.EventPlayerWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of EventPlayers to fetch.
   */
  orderBy?: Prisma.EventPlayerOrderByWithRelationInput | Prisma.EventPlayerOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing EventPlayers.
   */
  cursor?: Prisma.EventPlayerWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` EventPlayers from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` EventPlayers.
   */
  skip?: number
  distinct?: Prisma.EventPlayerScalarFieldEnum | Prisma.EventPlayerScalarFieldEnum[]
}

/**
 * EventPlayer create
 */
export type EventPlayerCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the EventPlayer
   */
  select?: Prisma.EventPlayerSelect<ExtArgs> | null
  /**
   * Omit specific fields from the EventPlayer
   */
  omit?: Prisma.EventPlayerOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EventPlayerInclude<ExtArgs> | null
  /**
   * The data needed to create a EventPlayer.
   */
  data: Prisma.XOR<Prisma.EventPlayerCreateInput, Prisma.EventPlayerUncheckedCreateInput>
}

/**
 * EventPlayer createMany
 */
export type EventPlayerCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many EventPlayers.
   */
  data: Prisma.EventPlayerCreateManyInput | Prisma.EventPlayerCreateManyInput[]
}

/**
 * EventPlayer createManyAndReturn
 */
export type EventPlayerCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the EventPlayer
   */
  select?: Prisma.EventPlayerSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the EventPlayer
   */
  omit?: Prisma.EventPlayerOmit<ExtArgs> | null
  /**
   * The data used to create many EventPlayers.
   */
  data: Prisma.EventPlayerCreateManyInput | Prisma.EventPlayerCreateManyInput[]
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EventPlayerIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * EventPlayer update
 */
export type EventPlayerUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the EventPlayer
   */
  select?: Prisma.EventPlayerSelect<ExtArgs> | null
  /**
   * Omit specific fields from the EventPlayer
   */
  omit?: Prisma.EventPlayerOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EventPlayerInclude<ExtArgs> | null
  /**
   * The data needed to update a EventPlayer.
   */
  data: Prisma.XOR<Prisma.EventPlayerUpdateInput, Prisma.EventPlayerUncheckedUpdateInput>
  /**
   * Choose, which EventPlayer to update.
   */
  where: Prisma.EventPlayerWhereUniqueInput
}

/**
 * EventPlayer updateMany
 */
export type EventPlayerUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update EventPlayers.
   */
  data: Prisma.XOR<Prisma.EventPlayerUpdateManyMutationInput, Prisma.EventPlayerUncheckedUpdateManyInput>
  /**
   * Filter which EventPlayers to update
   */
  where?: Prisma.EventPlayerWhereInput
  /**
   * Limit how many EventPlayers to update.
   */
  limit?: number
}

/**
 * EventPlayer updateManyAndReturn
 */
export type EventPlayerUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the EventPlayer
   */
  select?: Prisma.EventPlayerSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the EventPlayer
   */
  omit?: Prisma.EventPlayerOmit<ExtArgs> | null
  /**
   * The data used to update EventPlayers.
   */
  data: Prisma.XOR<Prisma.EventPlayerUpdateManyMutationInput, Prisma.EventPlayerUncheckedUpdateManyInput>
  /**
   * Filter which EventPlayers to update
   */
  where?: Prisma.EventPlayerWhereInput
  /**
   * Limit how many EventPlayers to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EventPlayerIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * EventPlayer upsert
 */
export type EventPlayerUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the EventPlayer
   */
  select?: Prisma.EventPlayerSelect<ExtArgs> | null
  /**
   * Omit specific fields from the EventPlayer
   */
  omit?: Prisma.EventPlayerOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EventPlayerInclude<ExtArgs> | null
  /**
   * The filter to search for the EventPlayer to update in case it exists.
   */
  where: Prisma.EventPlayerWhereUniqueInput
  /**
   * In case the EventPlayer found by the `where` argument doesn't exist, create a new EventPlayer with this data.
   */
  create: Prisma.XOR<Prisma.EventPlayerCreateInput, Prisma.EventPlayerUncheckedCreateInput>
  /**
   * In case the EventPlayer was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.EventPlayerUpdateInput, Prisma.EventPlayerUncheckedUpdateInput>
}

/**
 * EventPlayer delete
 */
export type EventPlayerDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the EventPlayer
   */
  select?: Prisma.EventPlayerSelect<ExtArgs> | null
  /**
   * Omit specific fields from the EventPlayer
   */
  omit?: Prisma.EventPlayerOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EventPlayerInclude<ExtArgs> | null
  /**
   * Filter which EventPlayer to delete.
   */
  where: Prisma.EventPlayerWhereUniqueInput
}

/**
 * EventPlayer deleteMany
 */
export type EventPlayerDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which EventPlayers to delete
   */
  where?: Prisma.EventPlayerWhereInput
  /**
   * Limit how many EventPlayers to delete.
   */
  limit?: number
}

/**
 * EventPlayer.payments
 */
export type EventPlayer$paymentsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Payment
   */
  select?: Prisma.PaymentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Payment
   */
  omit?: Prisma.PaymentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PaymentInclude<ExtArgs> | null
  where?: Prisma.PaymentWhereInput
  orderBy?: Prisma.PaymentOrderByWithRelationInput | Prisma.PaymentOrderByWithRelationInput[]
  cursor?: Prisma.PaymentWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.PaymentScalarFieldEnum | Prisma.PaymentScalarFieldEnum[]
}

/**
 * EventPlayer without action
 */
export type EventPlayerDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the EventPlayer
   */
  select?: Prisma.EventPlayerSelect<ExtArgs> | null
  /**
   * Omit specific fields from the EventPlayer
   */
  omit?: Prisma.EventPlayerOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EventPlayerInclude<ExtArgs> | null
}
